### ISSUE TITLE
up-to-date programming results

### ISSUE THREAD

**Issue by jialin-song** [lapisrocks/LanguageAgentTreeSearch#23]
Dear authors,

I saw that you recently updated HumanEval results and there were a few directories for Mbpp results. Can you tell me which files I should use to get the latest results from your work for a fair comparison?

A second question is how to properly extract solutions from a log file? I assume it is using the "solution" field for each problem, is that correct? 

Thank you for your time

**Comment by andyz245** [comment]
Hi, thanks for reaching out. It is fine to use the results in the paper for comparison. The updated results were experiments on the latest GPT-4 model which we might not publish. The original results are in [test_mcts_hard_acc_full_4tst_temp_gpt4](https://github.com/andyz245/LanguageAgentTreeSearch/tree/main/programming/root/test_mcts_hard_acc_full_4tst_temp_gpt4). 

Yes, the solution field is the generated solution.
