### ISSUE TITLE
LATS for local model

### ISSUE THREAD

**Issue by cacayaya** [lapisrocks/LanguageAgentTreeSearch#24]
Hi there, your work is amazing! LATS could allow GPT-3.5 to outperform GPT-4. And nowadays many local models can have almost same performance as GPT-3.5, if your method could **add model input for local model beyond just GPT-4 API** that would be very useful for having a local model almost compatible with GPT-4!

**Comment by andyz245** [comment]
Hi thanks for reaching out! You can find implementations of lats in Llamaindex and Langchain, which supports many LLMs including local ones

https://docs.llamaindex.ai/en/latest/api_reference/agent/lats/

https://github.com/langchain-ai/langgraph/blob/main/examples/lats/lats.ipynb?ref=blog.langchain.dev
