### ISSUE TITLE
code for “rap”, "react" and "tot" in the webshop environment

### ISSUE THREAD

**Issue by George-Chia** [lapisrocks/LanguageAgentTreeSearch#27]
Thanks for your great work! 
Could you provide the code for “rap”, "react" and "tot" in the webshop environment for the convenience of reproduction？

**Comment by andyz245** [comment]
Hi, for WebShop, please use the official implementation from ReAct https://github.com/ysymyth/ReAct. RAP and ToT do not natively work on WebShop so we did not implement them here.
