### ISSUE TITLE
Use of hidden test cases in programming tasks 

### ISSUE THREAD

**Issue by henryhungle** [lapisrocks/LanguageAgentTreeSearch#28]
Thanks for releasing the code for this amazing work! 
I have the following questions regarding LATS in the programming domain: 
1. Use of hidden test to select the best solution
Should the best solution be selected based on the results of the generated test cases only? From this code, the best solution is selected as `item["solution"]` which is assigned to a solution passing all hidden test cases.
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/mcts.py#L215-L217
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/mcts.py#L239-L242
As a result, when evaluating again on the hidden test cases, the best solutions will be biased since some are filtered by hidden test cases already. 
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/mcts.py#L247-L249

2. Use of hidden test if solved initially 
Since we are reevaluating `is_passing` with hidden tests (in which the code can still fail), the `num_sucess` should be updated by `num_success += int(is_passing)`. Otherwise, the final `num_success` is biased by generated test cases (old `is_passing`) and might not be correct. 
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/mcts.py#L131
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/mcts.py#L135-L139
I think in DFS, the same procedure is implemented more correctly..
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/43901ce2fd21e3e3dda115f440a8ab75acab3574/programming/dfs.py#L124-L132

**Comment by andyz245** [comment]
Thanks! 

For 1. the best solution is updated for each question. If a question already passes the hidden test cases, then the search is terminated, and it is used as the final solution

For 2. this is indeed a bug, we fixed it for the paper, but I forgot to update the repository. The update has been pushed.
